version: '2'
services:
    edgeserver-postgresql:
        container_name: edgeserver-postgresql
        image: postgres:9.5.2
        # volumes:
        #     - ~/volumes/jhipster/EdgeServer/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=EdgeServer
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
